version: '3.8'

services:
  db:
    container_name: PostgreSQL
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initiation_files/init.sql:/docker-entrypoint-initdb.d/initiation_files/init.sql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword  

  web:
    container_name: User
    build:
      context: .
      dockerfile: user_management_container/Dockerfile
    command: >
      sh -c "
      python user_management/manage.py makemigrations &&
      python user_management/manage.py migrate &&
      python user_management/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=pong_db
      - DATABASE_USER=pong_user
      - DATABASE_PASSWORD=pong_password

  dashboard:
    container_name: Dashboard
    build:
      context: .
      dockerfile: dashboard_container/Dockerfile
    command: >
      sh -c "
      python dashboard/manage.py makemigrations &&
      python dashboard/manage.py migrate &&
      python dashboard/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - web
      - db

volumes:
  postgres_data:
