services:

  database:
    container_name: Database
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - "transcendance"
    ports:
      - "5432:5432"
    env_file:
      - .env


  nginx:
    container_name: Nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - "transcendance"
    depends_on:
      - profile
      - dashboard


  profile:
    container_name: User
    user: root
    volumes:
      - .profile:/var/lib/postgresql/
    build:
      context: .
      dockerfile: user/Dockerfile
    command: >
      sh -c "
      sleep 5 &&
      cd /app &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8200"
    expose:
      - "8080:8080"
      - 5432
    ports:
      - "8200:8200"
    networks:
      - "transcendance"
    depends_on:
      - database
    env_file:
      - .env


  dashboard:
    container_name: Dashboard
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    command: >
      sh -c "
      cd /app &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8100"
    expose:
      - "8080:8080"
    ports:
      - "8100:8100"
    networks:
      - "transcendance"

networks:
  transcendance:
    driver: bridge

volumes:
  postgres_data:
    driver: local