version: '3.8'

services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - "transcendance"
    depends_on:
      - profile
      - dashboard


  profile:
    container_name: User
    build:
      context: .
      dockerfile: user/Dockerfile
    command: >
      sh -c "
      cd /app &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8200"
    ports:
      - "8200:8200"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=pong_database
      - DATABASE_USER=pong_user
      - DATABASE_PASSWORD=pong_password
    networks:
      - "transcendance"


  dashboard:
    container_name: Dashboard
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    command: >
      sh -c "
      cd /app &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8100"
    ports:
      - "8100:8100"
    depends_on:
      - profile
    networks:
      - "transcendance"

networks:
  transcendance:
    driver: bridge